# Preparing Data

In [6]:
# import zipfile

# # Open the zip file
# with zipfile.ZipFile('archive.zip', 'r') as zip_ref:
#     # Extract all contents to a specific folder
#     zip_ref.extractall('data')

In [7]:
import pandas as pd
import numpy as np
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [8]:
data = pd.read_csv('IMDB Dataset.csv')

In [9]:
data

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [10]:
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [11]:
data['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

since this review contain the html tags

removing html tags and convert it into the lower casing

In [12]:
from bs4 import BeautifulSoup
data['review'] = data['review'].apply(
    lambda x : BeautifulSoup(x,"html.parser").get_text().lower()
)

In [13]:
data['review'][1]

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [14]:
data['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

removing the stopwords

custom stop words for the sentiment analysis

In [15]:

stop_words = {'a',
 'about',
 'above',
 'after',
 'again',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'd',
 'did',
 'do',
 'does',
 'doing',
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'has',
 'have',
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'it',
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'more',
 'most',
 'my',
 'myself',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [16]:
def remove_stopwords(text):
  words = text.split()
  return ' '.join(word for word in words if word not in stop_words)

In [17]:
data['review'] = data['review'].apply(remove_stopwords)

In [18]:
data['review'][1]

'wonderful little production. filming technique unassuming- old-time-bbc fashion gives comforting, sometimes discomforting, sense realism entire piece. actors extremely well chosen- michael sheen not "has got polari" voices pat too! truly see seamless editing guided references williams\' diary entries, not well worth watching terrificly written performed piece. masterful production one great master\'s comedy life. realism really comes home little things: fantasy guard which, rather use traditional \'dream\' techniques remains solid disappears. plays knowledge senses, particularly scenes concerning orton halliwell sets (particularly flat halliwell\'s murals decorating every surface) terribly well done.'

removing punctuations

In [19]:
import re

def remove_punctuation(text):
    return re.sub(r'[^\w\s]', '', text)

In [20]:
data['review'] = data['review'].apply(remove_punctuation)

In [21]:
data['review'][1]

'wonderful little production filming technique unassuming oldtimebbc fashion gives comforting sometimes discomforting sense realism entire piece actors extremely well chosen michael sheen not has got polari voices pat too truly see seamless editing guided references williams diary entries not well worth watching terrificly written performed piece masterful production one great masters comedy life realism really comes home little things fantasy guard which rather use traditional dream techniques remains solid disappears plays knowledge senses particularly scenes concerning orton halliwell sets particularly flat halliwells murals decorating every surface terribly well done'

Tokenization       -----------> nltk work_tokenization

In [22]:
from nltk.tokenize import word_tokenize
def tokenization(text):
    return word_tokenize(text)
data['review'] = data['review'].apply(tokenization)

In [23]:
data['review'][1]

['wonderful',
 'little',
 'production',
 'filming',
 'technique',
 'unassuming',
 'oldtimebbc',
 'fashion',
 'gives',
 'comforting',
 'sometimes',
 'discomforting',
 'sense',
 'realism',
 'entire',
 'piece',
 'actors',
 'extremely',
 'well',
 'chosen',
 'michael',
 'sheen',
 'not',
 'has',
 'got',
 'polari',
 'voices',
 'pat',
 'too',
 'truly',
 'see',
 'seamless',
 'editing',
 'guided',
 'references',
 'williams',
 'diary',
 'entries',
 'not',
 'well',
 'worth',
 'watching',
 'terrificly',
 'written',
 'performed',
 'piece',
 'masterful',
 'production',
 'one',
 'great',
 'masters',
 'comedy',
 'life',
 'realism',
 'really',
 'comes',
 'home',
 'little',
 'things',
 'fantasy',
 'guard',
 'which',
 'rather',
 'use',
 'traditional',
 'dream',
 'techniques',
 'remains',
 'solid',
 'disappears',
 'plays',
 'knowledge',
 'senses',
 'particularly',
 'scenes',
 'concerning',
 'orton',
 'halliwell',
 'sets',
 'particularly',
 'flat',
 'halliwells',
 'murals',
 'decorating',
 'every',
 'surface',
 'terribly',
 'well',
 'done']

stemming

In [24]:
# not required for sentiment analysis

In [25]:
data

                                                  review sentiment
0      [one, reviewers, mentioned, watching, 1, oz, e...  positive
1      [wonderful, little, production, filming, techn...  positive
2      [thought, wonderful, way, spend, time, hot, su...  positive
3      [basically, theres, family, little, boy, jake,...  negative
4      [petter, matteis, love, time, money, visually,...  positive
...                                                  ...       ...
49995  [thought, movie, right, good, job, wasnt, crea...  positive
49996  [bad, plot, bad, dialogue, bad, acting, idioti...  negative
49997  [catholic, taught, parochial, elementary, scho...  negative
49998  [going, disagree, previous, comment, side, mal...  negative
49999  [no, one, expects, star, trek, movies, high, a...  negative

[50000 rows x 2 columns]

In [26]:
y = data['sentiment'].map({
    'positive': 1,
    'negative': 0
})

In [27]:
data

                                                  review sentiment
0      [one, reviewers, mentioned, watching, 1, oz, e...  positive
1      [wonderful, little, production, filming, techn...  positive
2      [thought, wonderful, way, spend, time, hot, su...  positive
3      [basically, theres, family, little, boy, jake,...  negative
4      [petter, matteis, love, time, money, visually,...  positive
...                                                  ...       ...
49995  [thought, movie, right, good, job, wasnt, crea...  positive
49996  [bad, plot, bad, dialogue, bad, acting, idioti...  negative
49997  [catholic, taught, parochial, elementary, scho...  negative
49998  [going, disagree, previous, comment, side, mal...  negative
49999  [no, one, expects, star, trek, movies, high, a...  negative

[50000 rows x 2 columns]

text to number conversion    ---> using TF-IDF

In [28]:
data['review'] = data['review'].apply(lambda x: ' '.join(x))

In [29]:
data['review'][1]

'wonderful little production filming technique unassuming oldtimebbc fashion gives comforting sometimes discomforting sense realism entire piece actors extremely well chosen michael sheen not has got polari voices pat too truly see seamless editing guided references williams diary entries not well worth watching terrificly written performed piece masterful production one great masters comedy life realism really comes home little things fantasy guard which rather use traditional dream techniques remains solid disappears plays knowledge senses particularly scenes concerning orton halliwell sets particularly flat halliwells murals decorating every surface terribly well done'

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

x = tfidf.fit_transform(data['review'])

In [31]:
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5150046 stored elements and shape (50000, 222027)>

output is ready ---> directorly map the data

In [32]:
data['sentiment'].unique()

array(['positive', 'negative'], dtype=object)

In [33]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 50000, dtype: int64

data spliting

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [35]:
x_train.size

4115833

In [36]:
# from sklearn.naive_bayes import MultinomialNB

# model = MultinomialNB()

# model.fit(x_train, y_train)

# y_pred = model.predict(x_test)

In [37]:
# y_pred

In [38]:
from sklearn.metrics import accuracy_score, classification_report
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
models = {
    "Naive Bayes": MultinomialNB(),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Linear SVM": LinearSVC()
}

for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    print("\n", name)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

 Naive Bayes
Accuracy: 0.869
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      4961
           1       0.88      0.85      0.87      5039

    accuracy                           0.87     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.87      0.87      0.87     10000


 Logistic Regression
Accuracy: 0.8965
              precision    recall  f1-score   support

           0       0.91      0.88      0.89      4961
           1       0.89      0.91      0.90      5039

    accuracy                           0.90     10000
   macro avg       0.90      0.90      0.90     10000
weighted avg       0.90      0.90      0.90     10000


 Linear SVM
Accuracy: 0.8987
              precision    recall  f1-score   support

           0       0.90      0.89      0.90      4961
           1       0.89      0.91      0.90      5039

    accuracy                           0.90     10000
   macro avg       0.90      0.90      0.90     10000
weighted avg       0.90      0.90      0.90     10000

now svc is givng a good result so i try to improve to the accuracy of the model
|

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [40]:
# for ngram in [(1,1), (1,2), (1,3)]:

#     tfidf = TfidfVectorizer(
#         ngram_range=ngram,
#         min_df=2,
#         max_df=0.95,
#         sublinear_tf=True
#     )

#     x = tfidf.fit_transform(data['review'])

#     x_train, x_test, y_train, y_test = train_test_split(
#         x, y,
#         test_size=0.2,
#         random_state=42,
#         stratify=y
#     )

#     model = LinearSVC()
#     model.fit(x_train, y_train)

#     y_pred = model.predict(x_test)

#     print(
#         "Ngram:", ngram,
#         "Accuracy:", accuracy_score(y_test, y_pred)
#     )

In [41]:
# for ngram in [(1,4), (1,5), (1,6)]:

#     tfidf = TfidfVectorizer(
#         ngram_range=ngram,
#         min_df=2,
#         max_df=0.95,
#         sublinear_tf=True
#     )

#     x = tfidf.fit_transform(data['review'])

#     x_train, x_test, y_train, y_test = train_test_split(
#         x, y,
#         test_size=0.2,
#         random_state=42,
#         stratify=y
#     )

#     model = LinearSVC()
#     model.fit(x_train, y_train)

#     y_pred = model.predict(x_test)

#     print(
#         "Ngram:", ngram,
#         "Accuracy:", accuracy_score(y_test, y_pred)
#     )

accuracy/f1 score is more on ngram = (1,4)

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    ngram_range=(1, 4),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

x = tfidf.fit_transform(data['review'])

now its time for the checking c value

In [43]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report
for c in [0.01, 0.1, 0.5, 1, 2, 5, 10]:

    model = LinearSVC(C=c)
    model.fit(x_train, y_train)

    y_pred = model.predict(x_test)

    print(
        "C:", c,
        "Accuracy:", accuracy_score(y_test, y_pred)
    )

C: 0.01 Accuracy: 0.8683
C: 0.1 Accuracy: 0.898
C: 0.5 Accuracy: 0.9033
C: 1 Accuracy: 0.9006
C: 2 Accuracy: 0.8981
C: 5 Accuracy: 0.8931
C: 10 Accuracy: 0.8914

In [44]:
for c in [11,11.5,12, 13,15]:

    model = LinearSVC(C=c)
    model.fit(x_train, y_train)

    y_pred = model.predict(x_test)

    print(
        "C:", c,
        "Accuracy:", accuracy_score(y_test, y_pred)
    )

C: 11 Accuracy: 0.8909
C: 11.5 Accuracy: 0.8909
C: 12 Accuracy: 0.8908
C: 13 Accuracy: 0.8901
C: 15 Accuracy: 0.8897

# Pipeline

In [49]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

model = Pipeline([
    ('tfidf', TfidfVectorizer(
        ngram_range=(1, 4),
        min_df=2,
        max_df=0.95,
        sublinear_tf=True
    )),
    ('svm', LinearSVC(C=0.5))
])

In [50]:
X = data['review']
y = data['sentiment'].map({
    'positive': 1,
    'negative': 0
})

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [51]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9133
              precision    recall  f1-score   support

           0       0.92      0.91      0.91      5000
           1       0.91      0.92      0.91      5000

    accuracy                           0.91     10000
   macro avg       0.91      0.91      0.91     10000
weighted avg       0.91      0.91      0.91     10000

# testing on new data set

In [52]:
reviews = [
    "This movie was absolutely fantastic and I loved every minute of it.",
    "Terrible movie. The acting was horrible and the story was boring.",
    "It was okay, nothing special."
]

predictions = model.predict(reviews)

for review, prediction in zip(reviews, predictions):
    sentiment = "Positive" if prediction == 1 else "Negative"
    print(sentiment, ":", review)

Positive : This movie was absolutely fantastic and I loved every minute of it.
Negative : Terrible movie. The acting was horrible and the story was boring.
Negative : It was okay, nothing special.

In [53]:
import joblib
joblib.dump(model, "sentiment_model.pkl")

['sentiment_model.pkl']